#!/usr/bin/env python3
"""Generate Herwig/HwSim cards for the completed extended-scalar mass scans."""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path


MH_GEV = 125
EVENTS = 10_000
EXPECTED_COUNTS = {"direct": 42, "cascade": 441}


@dataclass(frozen=True)
class Point:
    scenario: str
    miota: int
    meta: int | None
    source_run: str
    lhe: Path

    @property
    def run_name(self) -> str:
        if self.scenario == "direct":
            return f"HW-gg_iota0_hhhh-miota_{self.miota:04d}"
        assert self.meta is not None
        return (
            "HW-gg_iota0_eta0eta0_hhhh"
            f"-miota_{self.miota:04d}-meta_{self.meta:04d}"
        )


def replace_one(text: str, pattern: str, replacement: str, label: str) -> str:
    result, count = re.subn(pattern, replacement, text, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected exactly one {label} line, found {count}")
    return result


def deterministic_seed(run_name: str) -> int:
    digest = hashlib.sha256(run_name.encode("utf-8")).digest()
    return int.from_bytes(digest[:8], "big") % 900_000_000 + 1


def discover_points(mg_root: Path) -> list[Point]:
    points: list[Point] = []
    direct_events = mg_root / "gg_iota0_hhhh" / "Events"
    cascade_events = mg_root / "gg_iota0_eta0eta0_hhhh" / "Events"

    direct_pattern = re.compile(r"scan_direct_miota_(\d+)")
    for directory in direct_events.glob("scan_direct_miota_*"):
        match = direct_pattern.fullmatch(directory.name)
        lhe = directory / "unweighted_events.lhe.gz"
        if not match or not lhe.is_file() or lhe.stat().st_size == 0:
            continue
        miota = int(match.group(1))
        if miota <= 4 * MH_GEV:
            raise RuntimeError(f"Direct point violates miota > 4 mh: {directory.name}")
        points.append(Point("direct", miota, None, directory.name, lhe.resolve()))

    cascade_pattern = re.compile(r"scan_cascade_miota_(\d+)_meta_(\d+)")
    for directory in cascade_events.glob("scan_cascade_miota_*_meta_*"):
        match = cascade_pattern.fullmatch(directory.name)
        lhe = directory / "unweighted_events.lhe.gz"
        if not match or not lhe.is_file() or lhe.stat().st_size == 0:
            continue
        miota, meta = map(int, match.groups())
        if not (miota > 4 * MH_GEV and meta > 2 * MH_GEV and miota > 2 * meta):
            raise RuntimeError(f"Cascade point violates its mass hierarchy: {directory.name}")
        points.append(Point("cascade", miota, meta, directory.name, lhe.resolve()))

    points.sort(key=lambda p: (p.scenario, p.miota, p.meta or -1))
    counts = {
        scenario: sum(point.scenario == scenario for point in points)
        for scenario in EXPECTED_COUNTS
    }
    if counts != EXPECTED_COUNTS:
        raise RuntimeError(f"Expected {EXPECTED_COUNTS} completed LHE points, found {counts}")
    return points


def render_card(template: str, point: Point, seed: int) -> str:
    text = template
    if "setup iota0 99926" not in text:
        eta_setup = "setup eta0 99925 eta0 0.0 0.0 0.0 0.0 0 0 0 1"
        if eta_setup not in text:
            raise RuntimeError("The c3-d4 template does not contain the expected eta0 setup")
        text = text.replace(
            eta_setup,
            eta_setup
            + "\n\ncreate ThePEG::ParticleData iota0"
            + "\nsetup iota0 99926 iota0 0.0 0.0 0.0 0.0 0 0 0 1",
            1,
        )

    text = replace_one(
        text,
        r"^set theLHReader:FileName\s+.*$",
        f"set theLHReader:FileName {point.lhe}",
        "LHE filename",
    )
    text = replace_one(
        text,
        r"^set theGenerator:NumberOfEvents\s+.*$",
        f"set theGenerator:NumberOfEvents {EVENTS}",
        "event-count",
    )
    text = replace_one(
        text,
        r"^set theGenerator:RandomNumberGenerator:Seed\s+.*$",
        f"set theGenerator:RandomNumberGenerator:Seed {seed}",
        "random-seed",
    )
    text = replace_one(
        text,
        r"^saverun\s+\S+\s+theGenerator\s*$",
        f"saverun {point.run_name} theGenerator",
        "saverun",
    )

    required = (
        "library HwSim.so",
        "set /Herwig/Analysis/HwSim:BTaggingMethod GhostBHadrons",
        "set /Herwig/Analysis/HwSim:RParameter 0.4",
        "decaymode h0->b,bbar; 1.0 1 /Herwig/Decays/Hff",
    )
    missing = [entry for entry in required if entry not in text]
    if missing:
        raise RuntimeError(f"Template is missing required c3-d4 settings: {missing}")

    meta_text = "none" if point.meta is None else str(point.meta)
    header = (
        "# Generated by prepare_herwig_mass_scan.py from the c3-d4 signal card.\n"
        f"# scenario={point.scenario} miota_GeV={point.miota} "
        f"meta_GeV={meta_text} seed={seed}\n"
    )
    return header + text


def write_generated(path: Path, content: str, force: bool) -> str:
    if path.exists():
        old = path.read_text()
        if old == content:
            return "unchanged"
        if not force:
            raise RuntimeError(f"Refusing to overwrite changed generated card: {path}")
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content)
    temporary.replace(path)
    return "written"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, help="QuadrupleHiggsAnalysis repository root")
    parser.add_argument("--force", action="store_true", help="Replace changed generated cards")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    script_dir = Path(__file__).resolve().parent
    repo = args.repo.resolve() if args.repo else script_dir.parents[1]
    campaign = repo / "HerwigSignalPoints" / "mass_scan_10k"
    mg_root = repo / "MG5_aMC_v3_5_16"
    template_path = repo / "HerwigSignalPoints" / "c3d4_10k" / "HW-run_gg_4h_4_0.0_0.0.in"
    template = template_path.read_text()
    points = discover_points(mg_root)

    for scenario in EXPECTED_COUNTS:
        (campaign / scenario / "events").mkdir(parents=True, exist_ok=True)
        (campaign / scenario / "logs").mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, object]] = []
    written = unchanged = 0
    for point in points:
        seed = deterministic_seed(point.run_name)
        scenario_dir = campaign / point.scenario
        card = scenario_dir / f"{point.run_name}.in"
        state = write_generated(card, render_card(template, point, seed), args.force)
        written += state == "written"
        unchanged += state == "unchanged"
        rows.append(
            {
                "scenario": point.scenario,
                "miota_GeV": point.miota,
                "meta_GeV": "" if point.meta is None else point.meta,
                "source_run": point.source_run,
                "lhe": str(point.lhe),
                "lhe_bytes": point.lhe.stat().st_size,
                "run_name": point.run_name,
                "seed": seed,
                "events": EVENTS,
                "card": str(card.relative_to(repo)),
                "output_root": str((scenario_dir / "events" / f"{point.run_name}.root").relative_to(repo)),
                "run_log": str((scenario_dir / "logs" / f"{point.run_name}.run.log").relative_to(repo)),
            }
        )

    manifest = campaign / "manifest.csv"
    with manifest.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    for scenario in ("direct", "cascade"):
        list_path = campaign / f"herwig_inputs_{scenario}.txt"
        paths = [row["card"] for row in rows if row["scenario"] == scenario]
        list_path.write_text("".join(f"{path}\n" for path in paths))
    (campaign / "herwig_inputs_all.txt").write_text(
        "".join(f"{row['card']}\n" for row in rows)
    )

    print(f"Prepared {len(rows)} cards: {written} written, {unchanged} unchanged")
    print(f"Direct: {EXPECTED_COUNTS['direct']}; cascade: {EXPECTED_COUNTS['cascade']}")
    print(f"Manifest: {manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
